-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

-- AUTHORS TABLE
CREATE TABLE Authors (
  AUTHOR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(215) NOT NULL,
  PRIMARY KEY (AUTHOR_ID)
) ENGINE=INNODB;

-- CUSTOMERS TABLE
CREATE TABLE Customers (
  CUSTOMER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215) NOT NULL,
  ADDRESS TEXT,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=INNODB;

-- BOOKS TABLE
CREATE TABLE Books (
  BOOK_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT UNSIGNED NOT NULL,
  PRICE DOUBLE NOT NULL,
  PUBLICATION_DATE DATE,
  PRIMARY KEY (BOOK_ID),
  INDEX IDX_BOOKS_AUTHOR_ID (AUTHOR_ID),
  CONSTRAINT FK_BOOKS_AUTHORS
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHORS (AUTHOR_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDERS TABLE
CREATE TABLE Orders (
  ORDER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INT UNSIGNED NOT NULL,
  ORDER_DATE DATE NOT NULL,
  PRIMARY KEY (ORDER_ID),
  INDEX IDX_ORDERS_CUSTOMER_ID (CUSTOMER_ID),
  CONSTRAINT FK_ORDERS_CUSTOMERS
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS (CUSTOMER_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDER_DETAILS TABLE
CREATE TABLE Order_Details (
  ORDERDETAILID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ORDER_ID INT UNSIGNED NOT NULL,
  BOOK_ID INT UNSIGNED NOT NULL,
  QUANTITY DOUBLE NOT NULL,
  PRIMARY KEY (ORDERDETAILID),
  INDEX IDX_ORDER_DETAILS_ORDER_ID (ORDER_ID),
  INDEX IDX_ORDER_DETAILS_BOOK_ID (BOOK_ID),
  CONSTRAINT FK_ORDER_DETAILS_ORDERS
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS (ORDER_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_ORDER_DETAILS_BOOKS
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOKS (BOOK_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- OPTIONAL INDEXES
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);
CREATE INDEX IDX_CUSTOMERS_EMAIL ON CUSTOMERS (EMAIL);
